management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
server.port=8081
spring.application.name=storyline-demo-start
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=always
jobrunr.dashboard.enabled=true
# optional: showcase the embedded dashboard feature
jobrunr.dashboard.type=embedded
jobrunr.background-job-server.enabled=true

# TODO Step 10: Configure Priority Queues - The chosen names will be visible on the Dashboard!
# Payments (High priority) are always processed before reports (Lower priority)

# TODO Step 11: Configure Dynamic Queues (Weighted Round-Robin)
# Amex cardholders get 5x more processing than Mastercard

# TODO Step 14: Server Tags
# This server handles internal payments (JobRunr Finance) only
# Configure a server to handle external payments (PayPal/Stripe)
# or start one as below:
# ./gradlew :demo-start:bootRun --args='--server.port=8081 --jobrunr.dashboard.enabled=false --jobrunr.background-job-server.tags=external'

# TODO Step 15: Configure Rate Limiters
# PayPal: Concurrent rate limiter (max 5 concurrent)
# Stripe: Sliding window rate limiter (max 10 per minute)
# Government reporting: Concurrent rate limiter (max 3 concurrent)

# TODO Step 18: Metrics (Prometheus/Micrometer)

# TODO Step 19: Tracing (Jaeger/OpenTelemetry)