management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
server.port=8081
spring.application.name=storyline-demo-start
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=always
jobrunr.dashboard.enabled=true
# optional: showcase the embedded dashboard feature
jobrunr.dashboard.type=embedded
jobrunr.background-job-server.enabled=true

# TODO Step 10: Priority Queues
# Payments (High priority) are always processed before reports (Lower priority)

# TODO Step 11: Dynamic Queues (Weighted Round-Robin)
# Amex cardholders get 5x more processing than Mastercard

# TODO step 10: add a rate limiter
# TODO step 11: observability support; add micrometer exposure
# TODO step 12: observability support; add tracing information to Jaeger
